# Pytest Configuration File

[pytest]

addopts =
    # ------------------------------
    # General Options
    # ------------------------------
    -v
    --browser=chromium
    --headed
    --base-url=https://tutorialsninja.com/demo/

    # ------------------------------
    # Captures and Reports (Debugging)
    # ------------------------------
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --alluredir=reports/allure-results